# Generated by Django 2.2.7 on 2019-12-02 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0005_auto_20191202_0149'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pack',
            unique_together={('name', 'project')},
        ),
    ]
