# Generated by Django 2.2.7 on 2019-12-02 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0006_auto_20191202_0240'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('name', 'batch')},
        ),
    ]
