# Generated by Django 2.2.7 on 2019-12-02 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0007_auto_20191202_0250'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('name', 'pack')},
        ),
    ]
