# Generated by Django 3.0.1 on 2020-01-03 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0010_projectuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='current',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pack',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
