# Generated by Django 3.0.1 on 2020-01-13 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0011_auto_20200103_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('mutable', models.BooleanField()),
                ('attrtype', models.CharField(choices=[('CHECKBOX', 'checkbox'), ('RADIO', 'radio'), ('TEXT', 'text'), ('NUMBER', 'number'), ('select', 'select'), ('MULTISELECT', 'multiselect')], max_length=32)),
                ('default_value', models.CharField(max_length=128)),
                ('values', models.CharField(max_length=4096)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.Project')),
            ],
        ),
        migrations.CreateModel(
            name='LabeledShape',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('frame', models.PositiveIntegerField()),
                ('shapetype', models.CharField(choices=[('RECTANGLE', 'rectangle'), ('POLYGON', 'polygon'), ('POLYLINE', 'polyline'), ('POINTS', 'points')], max_length=32)),
                ('points', models.TextField()),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.Label')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.Task')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LabeledShapeAttributeVal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=128)),
                ('shape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.LabeledShape')),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.AttributeSpec')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='attributespec',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.Label'),
        ),
        migrations.AlterUniqueTogether(
            name='attributespec',
            unique_together={('label', 'name')},
        ),
    ]
