# Generated by Django 3.0.2 on 2020-01-20 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0012_auto_20200113_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
