# Generated by Django 3.0.2 on 2020-01-22 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0014_auto_20200120_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributespec',
            name='attrtype',
            field=models.CharField(choices=[('checkbox', 'checkbox'), ('radio', 'radio'), ('text', 'text'), ('number', 'number'), ('select', 'select'), ('multiselect', 'multiselect')], max_length=32),
        ),
        migrations.AlterField(
            model_name='attributespec',
            name='default_value',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='attributespec',
            name='values',
            field=models.CharField(blank=True, max_length=4096),
        ),
    ]
