# Generated by Django 3.0.2 on 2020-03-03 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0015_auto_20200122_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='labeledshape',
            name='shape_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attributespec',
            name='attrtype',
            field=models.CharField(choices=[('checkbox', 'checkbox'), ('text', 'text'), (
                'number', 'number'), ('select', 'select'), ('multiselect', 'multiselect')], max_length=32),
        ),
        migrations.AlterField(
            model_name='labeledshape',
            name='shapetype',
            field=models.CharField(choices=[('rectangle', 'rectangle'), ('polygon', 'polygon'), (
                'polyline', 'polyline'), ('points', 'points')], max_length=32),
        ),
    ]
