# Generated by Django 3.0.2 on 2020-03-03 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0016_auto_20200303_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='maxshape_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
