# Generated by Django 3.0.2 on 2020-03-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0017_task_maxshape_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='project',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
