# Generated by Django 3.0.2 on 2020-03-11 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0018_video_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.Project'),
        ),
    ]
